Update maven.yml

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -34,9 +34,11 @@ jobs:
     runs-on: self-hosted
 
     steps:
-    - name: Debug solo
+    - name: Debug sudo
       run: |
+        echo "Running as: $(whoamI)"
         sudo -l
+        sudo -n /usr/bin/systemctl daemon-reload || echo "FAILED: daemon-reload"
     - name: Who am I?
       run: |
         echo "Running as: $(whoami)"
