Update maven.yml

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -37,10 +37,23 @@ jobs:
           -H "Accept: application/vnd.github+json" \
           -H "Authorization: Bearer ${{ secrets.HUB_TOKEN }}" \
           -H "X-GitHub-Api-Version: 2022-11-28" \
-          "https://api.github.com/repos/luney-sp-76/motreminder/actions/artifacts")
+          "https://api.github.com/repos/${{ github.repository }}/actions/artifacts")
         echo "Artifact JSON: $ARTIFACTS_JSON"
         LATEST_ARTIFACT_URL=$(echo "$ARTIFACTS_JSON" | jq -r '[.artifacts[] | select(.expired == false)] | sort_by(.created_at) | last | .archive_download_url')
-        echo "artifact_url=$LATEST_ARTIFACT_URL" >> $GITHUB_OUTPUT
+        echo "url=$LATEST_ARTIFACT_URL" >> $GITHUB_OUTPUT
+
+    - name: Deploy to VPS
+      uses: appleboy/ssh-action@v0.1.4
+      with:
+        host: ${{ secrets.HOST }}
+        username: ${{ secrets.USERNAME }}
+        key: ${{ secrets.SSH_PRIVATE_KEY }}
+        port: 22
+        script: |
+          echo "Downloading the most recent artifact from: ${{ steps.get-artifacts.outputs.url }}"
+          wget -vvv -O latest_artifact.zip "${{ steps.get-artifacts.outputs.url }}" || { echo "Download failed"; exit 1; }
+          unzip -o latest_artifact.zip -d ./extracted
+          echo "Deployment completed successfully."
 
     - name: Deploy to VPS
       uses: appleboy/ssh-action@v0.1.4
