Update maven.yml

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -31,16 +31,16 @@ jobs:
     needs: build
     runs-on: ubuntu-latest
     steps:
-    - name: Get Most Recent Artifact Download URL
+    - name: Get Most Recent Artifact ID
       run: |
-        ARTIFACTS_JSON=$(curl -s -L \
+        ARTIFACT_ID_JSON=$(curl -s -L \
           -H "Accept: application/vnd.github+json" \
           -H "Authorization: Bearer ${{ secrets.HUB_TOKEN }}" \
           -H "X-GitHub-Api-Version: 2022-11-28" \
           "https://api.github.com/repos/${{ github.repository }}/actions/artifacts")
-        echo "Artifact JSON: $ARTIFACTS_JSON"
-        LATEST_ARTIFACT_URL=$(echo "$ARTIFACTS_JSON" | jq -r '[.artifacts[] | select(.expired == false)] | sort_by(.created_at) | last | .archive_download_url')
-        echo "url=$LATEST_ARTIFACT_URL" >> $GITHUB_OUTPUT
+        ARTIFACT_ID=$(echo "$ARTIFACT_ID_JSON" | jq -r '[.artifacts[] | select(.expired == false)] | sort_by(.created_at) | last | .id')
+        echo "artifact_id=$ARTIFACT_ID" >> $GITHUB_ENV
+
 
     - name: Deploy to VPS
       uses: appleboy/ssh-action@v0.1.4
@@ -62,8 +62,13 @@ jobs:
         username: ${{ secrets.USERNAME }}
         key: ${{ secrets.SSH_PRIVATE_KEY }}
         port: 22
-        script: |
-          echo "Downloading the most recent artifact from: ${{ steps.get-url.outputs.artifact_url }}"
-          wget -vvv -O latest_artifact.zip "${{ steps.get-url.outputs.artifact_url }}"
+        script: 
+          if [[ -z "$ARTIFACT_ID" ]]; then
+        echo "Error: No valid artifact ID found."
+            exit 1
+          fi"
+            ARTIFACT_URL="https://api.github.com/repos/${{ github.repository }}/actions/artifacts/$ARTIFACT_ID/zip"
+        echo "Downloading artifact from: $ARTIFACT_URL"
+        wget -vvv -O latest_artifact.zip --header="Authorization: Bearer ${{ secrets.HUB_TOKEN }}" "$ARTIFACT_URL"
           unzip -o latest_artifact.zip -d ./extracted
           echo "Deployment completed successfully."
