Update maven.yml

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -69,3 +69,34 @@ jobs:
           rm -f latest_artifact.zip
           rm -rf ./extracted
           echo "Deployment completed successfully."
+         
+  deploy:
+    runs-on: ubuntu-latest
+    steps:
+    - name: Start Green Service
+      run: |
+        ssh -tt ${{ secrets.SSH_USER }}@${{ secrets.HOST }} 'sudo systemctl start motbookingreminder2.service'
+
+    - name: Update Nginx Configuration for Blue-Green Deployment
+      run: |
+        ssh -tt ${{ secrets.SSH_USER }}@${{ secrets.HOST }} '
+        export SERVICE_PORT=8081  # Set to 8081 for green deployment
+        envsubst '$SERVICE_PORT' < /path/to/motbookingreminder.conf.template > /etc/nginx/conf.d/motbookingreminder.conf
+        sudo nginx -s reload'
+
+    - name: Health Check Green Service
+      run: |
+        STATUS=$(curl -s -o /dev/null -w '%{http_code}' https://motbookingreminder.co.uk/healthcheck)
+        if [ "$STATUS" -ne 200 ]; then
+          echo "Health check failed for Green environment; status code: $STATUS"
+          ssh -tt ${{ secrets.SSH_USER }}@${{ secrets.HOST }} '
+          export SERVICE_PORT=8082  # Revert to 8082 for blue deployment
+          envsubst '$SERVICE_PORT' < /path/to/motbookingreminder.conf.template > /etc/nginx/conf.d/motbookingreminder.conf
+          sudo nginx -s reload'
+          exit 1
+        fi
+
+    - name: Confirm Deployment
+      run: |
+        echo "Green deployment successful and verified!"
+
