Update maven.yml

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -47,11 +47,10 @@ jobs:
         script: |
           set -e  # Stop the script if any command fails
           cd /home/paulolphert/
-          # Assuming ARTIFACT_URL is the URL to a zip file
-          wget -vvv -O latest_artifact.zip "$ARTIFACT_URL"
-          unzip latest_artifact.zip -d ./extracted
-          # Move the jar file to the target directory, adjust the pattern as necessary
-          mv ./extracted/*.jar ./target/rest-service-0.0.2-SNAPSHOT.jar
+          echo "Attempting to unzip latest_artifact.zip"
+          unzip -o -v latest_artifact.zip -d ./extracted || { echo "Failed to unzip"; exit 1; }
+          echo "Unzip successful, moving files..."
+          mv ./extracted/*.jar ./rest-service-0.0.2-SNAPSHOT.jar
           echo "Deployment completed successfully."
           rm -f latest_artifact.zip
           rm -rf ./extracted
